INSERT INTO USERS (NAME, SURNAME, EMAIL, LOGIN, PASSWORD)
VALUES ('алексей', 'верезубов', 'zverovik@yahoo.com', 'верезубов', '1');
INSERT INTO USERS (NAME, SURNAME, EMAIL, LOGIN, PASSWORD)
VALUES ('роман', 'гурчунов', 'gurchunov-1997@mail.ru', 'гурчунов', '1');
INSERT INTO USERS (NAME, SURNAME, EMAIL, LOGIN, PASSWORD)
VALUES ('александр', 'зенькович', 'sanyazenkovgomel@gmail.com', 'зенькович', '1');
INSERT INTO USERS (NAME, SURNAME, EMAIL, LOGIN, PASSWORD)
VALUES ('татьяна', 'ковганко', 'dr.lisa217@gmail.com', 'ковганко', '1');
INSERT INTO USERS (NAME, SURNAME, EMAIL, LOGIN, PASSWORD)
VALUES ('владимир', 'петрушенко', 'petrush@tut.by', 'петрушенко', '1');
INSERT INTO USERS (NAME, SURNAME, EMAIL, LOGIN, PASSWORD)
VALUES ('иван', 'семёнов', 'semen_gen@tut.by', 'семёнов', '1');
INSERT INTO USERS (NAME, SURNAME, EMAIL, LOGIN, PASSWORD)
VALUES ('игорь', 'ханануев', 'alatair8@mail.ru', 'ханануев', '1');
INSERT INTO USERS (NAME, SURNAME, EMAIL, LOGIN, PASSWORD)
VALUES ('андрей', 'чернушевич', ' a.charnushevich@gmail.com', 'чернушевич', '1');
INSERT INTO USERS (NAME, SURNAME, EMAIL, LOGIN, PASSWORD)
VALUES ('павел', 'унуковский', 'paulu@mail.ru', 'унуковский', '1');
INSERT INTO USERS (NAME, SURNAME, EMAIL, LOGIN, PASSWORD)
VALUES ('антон', 'снежков', 'anton_sniazhkou1@epam.com', 'снежков', '1');

INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('USER', 1);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('DEVELOPER', 1);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('MANAGER', 1);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('USER', 2);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('MANAGER', 2);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('USER', 3);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('MANAGER', 3);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('USER', 4);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('DEVELOPER', 4);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('TESTER', 4);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('USER', 5);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('DEVELOPER', 5);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('USER', 6);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('TESTER', 6);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('USER', 7);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('TESTER', 7);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('USER', 8);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('TESTER', 8);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('USER', 9);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('MANAGER', 9);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('TESTER', 9);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('USER', 10);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('ADMIN', 10);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('DEVELOPER', 10);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('MANAGER', 10);
INSERT INTO ROLES (ROLE, USER_ID)
VALUES ('TESTER', 10);



INSERT INTO BOOKS (TITLE, GENRE, AUTHOR)
VALUES ('BOOK_TITLE', 'BOOK_GENRE', 'BOOK_AUTHOR');
INSERT INTO BOOKS (TITLE, GENRE, AUTHOR)
VALUES ('BOOK_TITLE_2', 'BOOK_GENRE_2', 'BOOK_AUTHOR_2');


INSERT into TEST (DATA, MARK, USER_ID, DURATION, COMMENT)
VALUES ('2020-09-10', 3, 6, '4:10', 'прошёл отлично');
